# Generated by Django 3.2.4 on 2021-06-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Register', 'verbose_name_plural': 'Contacts'},
        ),
    ]
