# Generated by Django 3.2.4 on 2021-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='patient_id',
            new_name='card_ID',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='tel',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(help_text='Enter your First name, middle name then last name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=7),
        ),
    ]
